steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/streamlit-app', '.']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/streamlit-app']

- name: 'gcr.io/cloud-builders/gcloud'
  args: ['run', 'deploy', 'streamlit-app', '--image', 'gcr.io/$PROJECT_ID/streamlit-app', '--platform', 'managed', '--region', 'us-central1', '--allow-unauthenticated']

options:
  logging: CLOUD_LOGGING_ONLY  # You can also set this to NONE if you prefer not to log
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET  # Ensures logs are saved to your specified bucket

timeout: '10m'  # Optional: set a timeout for the build process
